version: 2
sources:
    - name: staging
    
      database: key-nebula-378813  # For bigquery
      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: rides
        - name: yellow_tripdata
          freshness:
            error_after: {count: 6, period: hour}

            